[package]
name = "replay_time-81-3"
version = "0.1.0"
authors = ["jjf <stevenjiang1110@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.2.24"